openapi: 3.0.0
info:
  title: User Authentication API
  description: API for user registration, login, and management
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/

paths:
  auth/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - country
                - email
                - password
                - role
              properties:
                userName:
                  type: string
                country:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                role:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error

  auth/login:
    post:
      summary: Login a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        "200":
          description: Successful login
        "400":
          description: Invalid credentials
        "500":
          description: Internal server error

  auth/users:
    get:
      summary: Get all users (Admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users
        "500":
          description: Internal server error

  auth/users/{id}:
    delete:
      summary: Delete a user (Admin only)
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: User not found
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
